library(tidyr)
library(dplyr)
library(ggplot2)
library(tidyverse)
library(psych)
setwd("C:/Users/19728/Desktop/EPPS 7313/Excel Files")
GSS1998 <- read.csv("Income by Education GSS.csv")
summary(GSS1998)
income <- GSS1998$Respondent.income.in.constant.dollars
income <- as.numeric(income)
yrs_educ <- GSS1998$Highest.year.of.school.completed
yrs_work_exp <- GSS1998$How.many.years.in.your.occupation
labor_status <- GSS1998$Labor.force.status
age <- GSS1998$Age.of.respondent
age <- as.numeric(age)
race <- GSS1998$Race.of.respondent
prop.table(race)
summary(age)
income_model <- lm(income~yrs_educ,data=GSS1998)
income_model
summary(income_model)
income_model2 <- lm(income~yrs_educ+yrs_work_exp,data=GSS1998)
summary(income_model2)
head(GSS1998)
ggplot(GSS1998,aes(yrs_educ,income))
+geom_point(aes(yrs_educ,income))
+labs(x="Years of Education",y="Income",
      title="Education and Income",
      subtitle="GSS 1998")
+geom_smooth(method="lm")
var.test(income~labor_status)
cor.test(yrs_educ,income,method="pearson")
desc(income)
cor.test(yrs_work_exp,income,method="pearson")
sd(years_of_education)
sd(income)
var.test(years_of_education,income)
boxplot(income)
boxplot(yrs_educ, add=TRUE, col=2)
plot(income_model)
descr(income)
sapply(income,FUN)
options(scipen=100)
options(digits=1)
stat.desc(GSS1998)
desc(yrs_educ)
count(labor_status)
stat(labor_status)
cor.test(yrs_educ,income,method="pearson")
cov(yrs_educ,yrs_work_exp)
plot(income_model)
table(race)
summary(age)

summary(yrs_educ)
summary(yrs_work_exp)
summary(income)
sd(yrs_educ)
sd(yrs_work_exp)
sd(income)
summary(GSS1998$income)
summary(income)
var(income)
var(yrs_educ)
table(income)
tbl <- table(income, yrs_educ) #contingency table created
chisq.test(tbl)
stat.desc(income)
stat.desc(yrs_educ)
stat.desc(yrs_work_exp)
stat.desc(income)
cor.test(yrs_educ,income,method="pearson")
